### PR TITLE
Throw an exception to force reconnection to the server

### PR DESCRIPTION
**Pull request by EricHogueZD**
Jira: https://zendesk.atlassian.net/browse/SCALE-3765
Doc: https://docs.google.com/document/d/1TsjINY4WOqWFPgZeWdTbSht58qVdsQoC-JjZuuuPb9M/edit

These errors happens during Amazon MQ maintenance. Throw an error to force reconnection like we for empty messages.

I used it locally. I was able to turn Rabbit on and off a few time and it reconnected. But I can't reproduce the exact error that triggers this in maintenances.

### CODE REVIEW

**Comment by dygcao** [comment]
Could you link some evidence during maintenance on the number of occurence on this error? 🙏

**Comment by EricHogueZD** [comment]
> Could you link some evidence during maintenance on the number of occurence on this error? 🙏

This is the monitor that track this error: https://zendesk.datadoghq.com/monitors/112704928?live=3m . The error was logged 352 times during the last pod23 maintenance. 

We can see that the spikes match with maintenances: https://zendesk.datadoghq.com/monitors/112326150?q=pod%3Apod23&live=3m

**Comment by dhayhak** [comment]
Is the PR ready again for review? IIRC, we were waiting for some additional tests? 🤔

**Comment by EricHogueZD** [comment]
> Is the PR ready again for review? IIRC, we were waiting for some additional tests? 🤔

The tests were not concluent. It did not change anything. I'll close it.

**Pull request closed without merging**
